run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell
    - gocritic

# Only include linters supported by golangci-lint 2.2.1
